name: Send Hello to Repo C
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  send_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Send Hello to Repo C
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.REPO_C_ACCESS_TOKEN }}" \
            -d '{"event_type": "hello-event", "client_payload": {"message": "hello"}}' \
            https://api.github.com/repos/adamzielinski972/testRepoC/dispatches
